import os
val = input("Enter commit text ")
print ("-----RUNNING 'git add .'-----")
os.system('git add .')
print ("-----RUNNING 'git status'-----")
os.system('git status')
print ("-----RUNNING " + 'git commit -m "'+val+'"-----')
os.system('git commit -m "'+val+'"')
print("-----RUNNING 'git push origin master'-----")
os.system('git push origin master')
print("-----RUNNING 'git status'-----")
os.system('git status')
print("-----RUNNING 'git ftp push'-----")
os.system('git ftp push')
